### ISSUE TITLE
Throwing an Ender Pearl anywhere in the dimension gives this

### ISSUE THREAD

**Issue by Afrocntrik** [TelepathicGrunt/Bumblezone-Fabric#11]
![2020-09-01_20 08 53](https://user-images.githubusercontent.com/11052983/91943114-0d5d7900-ecca-11ea-87fe-11f93a660fc8.png)
![2020-09-01_20 08 50](https://user-images.githubusercontent.com/11052983/91943120-0f273c80-ecca-11ea-87a6-7eb26bb93b0f.png)

**Comment by Afrocntrik** [comment]
This is probably intended but is there a way to disable?

**Comment by TelepathicGrunt** [comment]
Well, the reason you can't disable it is because it's a bug lmao. I need to fix it so the warning only happens when the enderpearl is thrown at a bee nest

**Comment by TelepathicGrunt** [comment]
Fixed in v2.2.2!
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric/files/3048105

**Comment by Afrocntrik** [comment]
Sweet thank you
