### ISSUE TITLE
Incompatible With Carpet Mod

### ISSUE THREAD

**Issue by IAmSneak** [TelepathicGrunt/Bumblezone-Fabric#13]
Fabric 1.16.2 Server
Java 11
Mods: Carpet, Bumblezone, Fabric API. All latest versions for 1.16.2
Crash Report:
[crash-2020-09-05_02.33.56-server.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5177629/crash-2020-09-05_02.33.56-server.txt)

**Comment by TelepathicGrunt** [comment]
I believe their mixin here is conflicting with mine
https://github.com/gnembon/fabric-carpet/blob/3167fe06f38053dc34bfab57e066de7a850b57d5/src/main/java/carpet/mixins/SpawnHelperMixin.java#L152-L173

https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/master/src/main/java/net/telepathicgrunt/bumblezone/mixin/PollenedBeeNaturalSpawnMixin.java

Maybe I can move my mixin...

**Comment by TelepathicGrunt** [comment]
v2.2.4 should fix this crash. Thank you for reporting this! :)
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric/files/3052555
