### ISSUE TITLE
Dimension scale not applied when exiting?

### ISSUE THREAD

**Issue by copygirl** [TelepathicGrunt/Bumblezone-Fabric#15]
On the CurseForge page you mention this:

> By default, traveling a block in this dimension is the same as traveling 10 block in the Overworld.

However, when testing, this didn't seem to be the case. I tried exiting the dimension and landed at about the same location in the overworld as I was in the Bumblezone. It seemed to created a new beehive when I did this. Additionally, the wording "by default" suggests that there would be a configuration option to allow changing the scale..? I did not find one.

**Comment by TelepathicGrunt** [comment]
You would need a datapack to change the coordinate scale of the dimension of the dimension's json file. 
https://github.com/TelepathicGrunt/Bumblezone-Fabric/blob/2660759219820429c8bf7729382cc9633e7fdaec/src/main/resources/data/the_bumblezone/dimension_type/the_bumblezone.json#L15

The scaling will only take effect for teleportation mode 1 in the configs if you leave the dimension and there is no beenest in the general area. (it'll teleport you to the beenest if it is nearby) If there is no Beenest nearby to snap the player's coordinate to when exiting the dimension, it'll spawn the player at the new coordinate exactly and spawn a beenest at your feet unless you turn off that generateBeenest config option.

I can double check to make sure the coordinate conversions is being done later. Was the config descriptions too unclear? I could attempt to see if I can reword it

**Comment by copygirl** [comment]
Is the coordinate scale supposed to be supplied in a datapack or is this an oversight?
(As I said the CurseForge page mentions 10 blocks being the default.)

I think the explanations are clear otherwise. If I understand correctly, for mode 1, the coordinate scaling is applied to the position in the Bumblezone (200,50 becomes 2000,500), then it looks for a suitable beenest nearby or creates one in the overworld?

**Comment by TelepathicGrunt** [comment]
The reason why it's a datapack thing instead of a config is because the jump of 1.15.2 to 1.16+ changed dimensions to make them json driven (well I could've made them in code but it would've be much more work lol). 

Here, this datapack should let you change the values can all. Just go into the json file and mess with it till the coordinate scale is what you want
[bumblezoneDim.zip](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5320340/bumblezoneDim.zip)

And yeah, it would like you said.  200, 50 to 2000, 500 and that's when it checks for a nearby beenest or makes a new one. I haven't had a chance yet to check to make sure the coordinates are indeed being converted correctly but they aren't, well that's a bug I gotta fix lol

**Comment by TelepathicGrunt** [comment]
Oh the coordinate conversion is broken lmao. Oops
I went from 100, 100 to 100, 100...

**Comment by copygirl** [comment]
I've started tinkering with data pack modifications for the modpack I'm working on so I'm becoming somewhat familiar. Thank you for providing an example however, and looking into the issue!

**Comment by TelepathicGrunt** [comment]
Just released 2.2.6 that fixed this bug! Thank you for reporting this! I surprised no one else opened an issue about this as the bug has been around since the initial 1.16.2 release lmao

https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric/files/3071293

**Comment by TelepathicGrunt** [comment]
Last thing, I just looked at the mod description and many was it out of date. Sorry about that! I updated it to mention that the config is now in-game and some options are to be controlled by datapacks. Hopefully this wont confuse anymore people

**Comment by copygirl** [comment]
Thank you for your time - and the mod, of course! :green_heart:
