### ISSUE TITLE
Server crashes when throwing enderpearls into bee nest

### ISSUE THREAD

**Issue by laxotor** [TelepathicGrunt/Bumblezone-Fabric#19]
[2020-12-12-6.log](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5683004/2020-12-12-6.log)
[crash-2020-12-12_20.46.27-server.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/5683006/crash-2020-12-12_20.46.27-server.txt)

It works fine in singleplayer, but crashes in multiplayer

**Comment by TelepathicGrunt** [comment]
Dang tags. Fix will be soon. That you for reporting!

**Comment by TelepathicGrunt** [comment]
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric/files/3136995
fixed now! Thank you!
