### ISSUE TITLE
Wrath of Hive Duration Units?

### ISSUE THREAD

**Issue by decon-structed** [TelepathicGrunt/Bumblezone-Fabric#2]
In the config you say,
```json
	/* ##############################################################
	   ##############################################################
	   
	   How long bees will keep their effects for (speed, absorption, strength).
	   
	   Note: This is not in seconds at all. And bee's anger will remain.
	   Only the boosts given to the bees will be gone.
	*/
	"howLongWrathOfTheHiveLasts": 350
```

It they're not in seconds, what are they? Could the config file be updated to clarify for others?

**Comment by TelepathicGrunt** [comment]
It seems to be based on ticks. At the time, I didn't know the conversion of the unit to actual time but now I believe it is generally 20 ticks per second. I can do some testing and update the comment there once I confirm this. thank you for reminding me of this lol

**Comment by TelepathicGrunt** [comment]
Dang I forgot about this completely! Config will now says the duration config is in ticks and 20 ticks equal 1 second. Sorry about that. Will close this now as this will be in next update!
