### ISSUE TITLE
Nether and End portal doesn't work anymore after removing mod from server

### ISSUE THREAD

**Issue by HumanMint** [TelepathicGrunt/Bumblezone-Fabric#20]
Our server had an issue with bumblezone 2.2.12 where when we threw an ender pearl literally anywhere it would crash the server with this log
`---- Minecraft Crash Report ----
// My bad.

Time: 12/12/20 1:58 PM
Description: Ticking entity

java.lang.IllegalStateException: Tag the_bumblezone:blacklisted_teleportable_hive_blocks used before it was bound
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:72)
	at net.minecraft.class_5120$class_5121.method_15141(class_5120.java:83)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportation.isValidBeeHive(PlayerTeleportation.java:181)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportation.runEnderpearlImpact(PlayerTeleportation.java:128)
	at net.minecraft.class_1684.handler$bgl000$onPearlHit(class_1684.java:519)
	at net.minecraft.class_1684.method_7488(class_1684.java)
	at net.minecraft.class_1682.method_5773(class_1682.java:67)
	at net.minecraft.class_1684.method_5773(class_1684.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_5120$class_5121.method_26776(class_5120.java:72)
	at net.minecraft.class_5120$class_5121.method_15141(class_5120.java:83)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportation.isValidBeeHive(PlayerTeleportation.java:181)
	at net.telepathicgrunt.bumblezone.entities.PlayerTeleportation.runEnderpearlImpact(PlayerTeleportation.java:128)
	at net.minecraft.class_1684.handler$bgl000$onPearlHit(class_1684.java:519)
	at net.minecraft.class_1684.method_7488(class_1684.java)
	at net.minecraft.class_1682.method_5773(class_1682.java:67)
	at net.minecraft.class_1684.method_5773(class_1684.java:88)
	at net.minecraft.class_3218.method_18762(class_3218.java:621)

-- Entity being ticked --
Details:
	Entity Type: minecraft:ender_pearl (net.minecraft.class_1684)
	Entity ID: 1071
	Entity Name: Thrown Ender Pearl
	Entity's Exact location: 660.71, 74.83, 792.12
	Entity's Block location: World: (660,74,792), Chunk: (at 4,4,8 in 41,49; contains blocks 656,0,784 to 671,255,799), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.48, -0.56, -0.71
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_3218.method_18765(class_3218.java:411)

-- Affected level --
Details:
	All players: 2 total; [class_3222['HumanMint'/246, l='ServerLevel[world]', x=631.24, y=63.00, z=835.92], class_3222['Sn0k'/677, l='ServerLevel[world]', x=631.87, y=63.00, z=838.74]]
	Chunk stats: ServerChunkCache: 2025
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-64,199,-240), Chunk: (at 0,12,0 in -4,-15; contains blocks -64,0,-240 to -49,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 5150551 game time, 5559531 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 1209 (now: false), thunder time: 48241 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6357707368 bytes (6063 MB) / 8206155776 bytes (7826 MB) up to 8206155776 bytes (7826 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms8G -Xmx8G
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advdebug: Advancements Debug 2.2.0
		adventurez: AdventureZ 1.1.5
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		arstheurgia: Ars Theurgia 1.0.5
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		astromine: Astromine 1.11.4+fabric-1.16.3
		astromine-core: Astromine: Core 1.11.4+fabric-1.16.3
		astromine-discoveries: Astromine: Discoveries 1.11.4+fabric-1.16.3
		astromine-foundations: Astromine: Foundations 1.11.4+fabric-1.16.3
		astromine-technologies: Astromine: Technologies 1.11.4+fabric-1.16.3
		astromine-transportations: Astromine: Transportations 1.11.4+fabric-1.16.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bambootweaks: Bamboo Tweaks unspecified
		battletowers: Battle Towers 3.3.1-beta-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.7.1-beta
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betternether: Better Nether 5.0.4
		biomemakeover: Biome Makeover 1.16.4-1.1.5
		blade: Blade 2.0.0
		blockus: Blockus 1.6.8+1.16.4
		blue_endless_jankson: jankson +
		byg: BYG 1.1.3
		campanion: Campanion 1.3.0+build.49
		cardinal-components: Cardinal Components API 2.7.9
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-block: Cardinal Components API (blocks) 2.7.9
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-level: Cardinal Components API (world saves) 2.7.9
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.7.9
		cardinal-components-world: Cardinal Components API (worlds) 2.7.9
		chainmail: Chainmail 0.5.0
		chains: Chains-Link 1.16.2-2.0.1
		charm: Charm 2.1.6
		charmonium: Charmonium 2.1.4
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cleancut: CleanCut mc1.16-2.1-fabric
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		couplings: Couplings 1.3.1
		crookedcrooks: Crooked Crooks 1.3.3+1.16.4
		croptopia: Croptopia 1.0.5-1.16.3-FABRIC
		dawn: Dawn API 1.5.4
		environmentalcreepers: Environmental Creepers 1.6.1
		expandedstorage: ExpandedStorage 5.6.31
		extraorigins: Extra Origins 1.16.4-4
		fabric: Fabric API 0.28.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.9+a03e98793a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+ffb68a873a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.0+4358fbc63a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.7+a03e98793a
		fabric-networking-v0: Fabric Networking (v0) 0.3.0+a03e98793a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.2+a03e98793a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabricloader: Fabric Loader 0.10.8
		fallflyinglib: FallFlyingLib 1.1.0
		falling_tree: FallingTree 2.7.0
		fatxporbs: Fat Experience Orbs 0.0.9
		fdlink: Fabric <-> Discord Link 0.7.18
		fdlink_1_15_2: Fabric <-> Discord Link 0.7.18
		fdlink_1_16: Fabric <-> Discord Link 0.7.18
		fdlink_common: Fabric <-> Discord Link 0.7.18
		fermion: Fermion 2.1.191
		fermion-modkeys: Fermion Modifier Keys 1.8.180-snapshot
		fiber: fiber 0.23.0-1
		flamingo_ooo: Flamingo, oh, oh, oh... 1.0.4-MC1.16.3-fabric
		flonters: Flonters 1.1.1+1.16.2
		flora-doubling: Flora Doubling 1.3.0+1.16.4-fabric
		geckolib: Geckolib 2.0.0
		givemehats: Give Me Hats! 1.3
		glassdoor: Glass Doors 1.5.0-1.16
		glassential: Glassential 1.16.4-1.1.5
		glowsquid: Glowsquid 1.1
		gravestones: Gravestones v1.7
		hard-hat-steve: Hard Hat Steve 1.2.0
		harvest: Harvest 1.2.12
		harvest_scythes: Harvest Scythes 1.0.4
		ignis-fatuus: Ignis Fatuus 1.1.0
		improved-stations: Improved Stations 2.0.3
		indrev: Industrial Revolution 1.7.15-BETA
		inmis: Inmis 2.0.1-beta-1.16.2
		inventorysorter: Inventory Sorter 1.7.4-1.16
		jankson: Jankson 3.0.1+j1.2.0
		kubejs: KubeJS 1.5.5
		kyrptconfig: Kytpt Config 1.1.6-1.16
		lapisreserve: Lapis Reserve 1.0.6
		leadvillagers: Lead Villagers 2.1.0+mc1.16.1
		libblockattributes: LibBlockAttributes 0.8.4
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.4
		libblockattributes_items: LibBlockAttributes (Items) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		magna: Magna 1.4.3-1.16.2
		mcdict: MCDict 2.0.1+1.16.4
		mcdw: MC Dungeons Weapons 2.0.7
		megane: megane 3.0.7+1.16.4
		megane-api: megane-api 3.0.7+1.16.4
		megane-impl: megane-impl 3.0.7+1.16.4
		megane-runtime: megane-runtime 3.0.7+1.16.4
		minecraft: Minecraft 1.16.4
		modern_industrialization: Modern Industrialization 0.3.9
		modid: Damage Tilt 1.16-fabric-0.1.0
		moreberries: More Berries 1.3.4
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		net_dv8tion_jda: JDA 4.2.0_191
		net_sf_trove4j_trove4j: trove4j 3.0.3
		netherite_plus: Netherite Plus Mod 1.1.0
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_joml_joml: joml 1.9.25
		org_json_json: json 20170516
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		origins: Origins 0.4.5
		origins-classes: Origins: Classes 1.1.0
		patchouli: Patchouli 1.16.2-44-FABRIC
		pehkui: Pehkui 1.6.2+1.16.3
		phosphor: Phosphor 0.6.0+build.7
		piglib: Piglib 1.0.1
		polymorph: Polymorph 0.0.5-1.16.3
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		reborncore: Reborn Core 4.6.1+build.97
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		respawnablepets: Respawnable Pets 1.16.4-1
		sandwichable: Sandwichable 1.1.2
		shapes: Shapes 2.0.0+build.10
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		sit: Sit 1.16.2-9
		staffofbuilding: Staff of Building 1.2.3-1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structure-helpers: Structure Helpers 3.0.0
		team_reborn_energy: Energy 0.1.1
		techreborn: Tech Reborn 3.7.1+build.162
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.3
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.3
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		the_bumblezone: The Bumblezone - Fabric 1.16.3-2.2.12
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		totemmod: Wither Totems Mod 0.3.2
		trinkets: Trinkets 2.6.7
		vanilla-hammers: Vanilla Hammers 3.0.1-1.16.3
		vanillaexcavators: Vanilla Excavators 1.1.0
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		woodenhoppers: Wooden Hoppers 1.0.0
		wrenchable: Wrenchable 1.0.0+1.16.1
		xaerominimap: Xaero's Minimap 20.29.0
		xaeroworldmap: Xaero's World Map 1.11.4
		xpstorage: XP Storage 1.1.1+1.16.4
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.16.4-Fabric-1
		zoob: Monster Of The Ocean Depths 2.5.0
	Player Count: 3 / 69; [class_3222['HumanMint'/246, l='ServerLevel[world]', x=631.24, y=63.00, z=835.92], class_3222['PurpleBacon'/249, l='ServerLevel[world]', x=152.30, y=83.00, z=1290.31], class_3222['Sn0k'/677, l='ServerLevel[world]', x=631.87, y=63.00, z=838.74]]
	Data Packs: vanilla (incompatible), fabric/adorn, fabric/adventurez, fabric/arstheurgia, fabric/artifacts, fabric/artofalchemy, fabric/astromine-core, fabric/astromine-discoveries, fabric/astromine-foundations, fabric/astromine-technologies, fabric/astromine-transportations, fabric/bambootweaks, fabric/battletowers, fabric/bedspreads, fabric/betterend, fabric/betternether, fabric/biomemakeover, fabric/blockus, fabric/byg, fabric/campanion, fabric/charm (incompatible), fabric/crookedcrooks, fabric/croptopia, fabric/expandedstorage, fabric/extraorigins, fabric/fabric-furnaces, fabric/fabric-tool-attribute-api-v1, fabric/flamingo_ooo, fabric/flonters, fabric/flora-doubling, fabric/glassdoor, fabric/glassential, fabric/glowsquid, fabric/gravestones, fabric/hard-hat-steve (incompatible), fabric/harvest, fabric/ignis-fatuus, fabric/improved-stations, fabric/indrev, fabric/inmis, fabric/kubejs (incompatible), fabric/libcd, fabric/mcdw, fabric/modern_industrialization, fabric/moreberries, fabric/mostructures, fabric/netherite_plus, fabric/netheritehorsearmor, fabric/origins, fabric/origins-classes, fabric/piglib, fabric/repurposed_structures, fabric/respawnablepets, fabric/sandwichable, fabric/staffofbuilding, fabric/structure-helpers, fabric/techreborn, fabric/terrestria, fabric/the_bumblezone, fabric/totemmod, fabric/trinkets, fabric/vanilla-hammers, fabric/vanillaexcavators, fabric/villagerhats, fabric/wolveswitharmor, fabric/woodenhoppers, fabric/xpstorage, fabric/zoob, file/afk display v1.1.0.zip, file/armor statues v2.8.1.zip, file/player head drops v1.1.0.zip, file/villager workstation highlights v1.1.0.zip, file/anti enderman grief v1.1.0.zip, file/cauldron concrete v2.0.3.zip, file/double shulker shells v1.3.0.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

So we decided it would be best to uninstall that mod from the server and restart it without it. Ever since then, ANY portals won't work (going in them just doesn't do anything) and even after installing the latest version of bumblezone 2.2.13 the portals don't work at all.

I understand that this isn't necessarily a bug that is caused without bumblezone installed but i wanted to figure out what caused it to stop the portals from working ever since we uninstalled this mod.

Thanks!

**Comment by TelepathicGrunt** [comment]
Oh shoot I missed this report. Anyway, the issue you faced is this mojang bug which I do not know of any mod that fixes it https://bugs.mojang.com/browse/MC-197860

Basically, removal of any dimension mod or datapack dimension may break the nether and end. There may be a way for you to restore them by editing the level.dat file. Maybe make a new world and copy the dimension info from that level.dat to the broken one 

That's why I have this warning on my mod page to backup your worlds before testing new dimension mods.
![image](https://user-images.githubusercontent.com/40846040/104195826-16d1bd00-53f1-11eb-91a2-371ab7506747.png)

Sorry but there's nothing I can really do on my end. :(

**Comment by HumanMint** [comment]
Thanks for the notice and helpful info! We decided to just reset since the world was a day old back then. I will make sure to be careful from next time. I appreciate the work that you're putting into this project and hope for the best!
