### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by srnyx** [TelepathicGrunt/Bumblezone-Fabric#23]
Is it safe to remove the mod after already playing with it for a bit?
Like will it corrupt anything?

**Comment by TelepathicGrunt** [comment]
There's only one main concern and that's this mojang bug https://bugs.mojang.com/browse/MC-197860

Removing a dimension mod may break the nether and end dimension. but there's a workaround for that. First, backup your world. Then enter the world. Exit. Then open the level.dat file for that world with NBTExplorer, open WorldGenSettings section, and delete the dimensions package entirely. Enter world. Exit. Enter the world twice and all dimensions are back. You can check by doing `/execute in` and the vanilla dimensions should be visible again

**Comment by srnyx** [comment]
> There's only one main concern and that's this mojang bug https://bugs.mojang.com/browse/MC-197860
> 
> Removing a dimension mod may break the nether and end dimension. but there's a workaround for that. First, backup your world. Then enter the world. Exit. Then open the level.dat file for that world with NBTExplorer, open WorldGenSettings section, and delete the dimensions package entirely. Enter world. Exit. Enter the world twice and all dimensions are back. You can check by doing `/execute in` and the vanilla dimensions should be visible again

What if I have other mods on my server like BetterEnd and BYG?

**Comment by TelepathicGrunt** [comment]
that does complicate thing. In WorldGenSettings's dimension package, find bumblezone and delete just that entry alone and see if that works

**Comment by srnyx** [comment]
> that does complicate thing. In WorldGenSettings's dimension package, find bumblezone and delete just that entry alone and see if that works

So I'd do this?
1. Backup world
2. Enter the world
3. Exit the world
4. Open the level.dat file for that world
5. Open the WorldGenSettings section and delete the Bumblezone section
6. Enter the world
7. Exit the world
8. Enter the world again and all dimensions are back. You can check by doing /execute in and the vanilla dimensions should be visible again

**Comment by TelepathicGrunt** [comment]
You can skip step 2 and 3. In fact, if removing just the bumblezone section works, everything should be ok when you enter the world in step 6. I never done this myself before so idk if it will work

**Comment by srnyx** [comment]
> You can skip step 2 and 3. In fact, if removing just the bumblezone section works, everything should be ok when you enter the world in step 6. I never done this myself before so idk if it will work

Alright. And at which step should I remove the mod from the mods folder?

**Comment by TelepathicGrunt** [comment]
after backing up

**Comment by TelepathicGrunt** [comment]
Basically:
- backup
- remove mod
- delete bumblezone from WorldGenSettings's dimension package in level.dat
- Enter world and see if it worked and the other dimensions are safe

**Comment by TelepathicGrunt** [comment]
Gonna close this now as this should be resolved. lmk if you are still having issues

**Comment by srnyx** [comment]
> Basically:
> 
> * backup
> * remove mod
> * delete bumblezone from WorldGenSettings's dimension package in level.dat
> * Enter world and see if it worked and the other dimensions are safe

It seems like this worked. I hope it didn't break anything...
