### ISSUE TITLE
BeehiveBlockMixin from Requiem crashes with Bumblezone 

### ISSUE THREAD

**Issue by JustaFloatingEyeYT** [TelepathicGrunt/Bumblezone-Fabric#28]
Description: If the mod is installed in my fabric modpack on forge using jumploader (it isn't published as only I use the modpack) it will crash the game right after I press play on the Minecraft launcher, no Minecraft loading screen, unsure why.

Version of the mod: Latest version currently (2.4.2)

Forge version: Latest version currently (36.1.16)

MC Version: 1.16.5

List of mods in modpack (Got a bit lazy here so I just copied and pasted the jar files' names):

Monster-of-the-ocean-depths-3.1-1.16.5.jar
alaskanativecraft-1.1.1.jar
architectury-1.12.149-fabric.jar
betterdroppeditems-1.2.4-1.16.2.jar
better-end-0.9.6-pre.jar
better-nether-5.0.7.jar
bitsandchisels-2.1.4.jar
caelus-fabric-0.0.15-1.16.4.jar
cheeky-monkeys-0.3.0-alpha.jar
cleancut-mc1.16-2.2-forge.jar
cloth-config-4.11.19-fabric.jar
cosmetic-armor-1.0.0.jar
curios-fabric-0.0.13-1.16.5.jar
Earth2Java-1.7.0+1.16.4.jar
ecotones-0.7.2.jar
origins-plus-0.0.2.jar
extraorigins-1.16.5-11.jar
fabric-api-0.34.1+1.16.jar
fabric-language-kotlin-1.6.0+kotlin.1.5.0.jar
wraith-waystones-1.1.1.1.jar
fishtraps-0.1.3.jar
Flamingo-oh-oh-oh-1.0.4-MC1.16.3-fabric.jar
geckolib-fabric-1.16.5-3.0.34.jar
genesis_forge_1.1.jar
GentleFawn-1.1.4-MC1.16.5-fabric.jar
illuminations-1.5.1.jar
immersive-portals-0.90-mc1.16.5-fabric.jar
improved-stations-2.0.3.jar
jumploader-2.1.3.jar
luxfurnituremod-0.0.2.jar
MiningDimensions_Fabric_1.16.5-1.0.4.jar
mostructures-1.1.1+mc.1.16.5.jar
moborigins-1.4.0.jar
modmenu-1.16.9.jar
byg-1.1.7.jar
Origins-1.16.5-0.7.1.jar
Origins-Classes-1.16.5-1.1.1.jar
Pehkui-2.1.0+21w18a.jar
PresenceFootsteps-r29+1.16.4.jar
rare-ice-0.2.2.jar
repurposed_structures-1.16.5-1.10.5-fabric.jar
requiem-1.6.3.jar
RoughlyEnoughItems-5.11.218.jar
simplexterrain-0.7.2.jar
the_bumblezone_fabric-1.16.5-2.4.2.jar
theparakeetmod-Fabric-1.16.3-1.0.6.jar
untitledduckmod-0.1.1-fabric.jar
worldedit-mod-7.2.5-dist.jar
Xaeros_Minimap_21.8.0_Forge_1.16..5.jar
XaerosWorldMap_1.13.4_Forge_1.16.5.jar
YUNG's API (Fabric)
YungsApi-1.16.5-Fabric-5.jar
YUNG's Better Caves (Fabric)
BetterCaves-Fabric-1.16.5-1.1.jar
YUNG's Better Mineshafts (Fabric)

Attatched file is latest.log file:

[latest.log](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/6448482/latest.log)

**Comment by JustaFloatingEyeYT** [comment]
After some mods I have were updated it was fixed :D must have been a comfliction.

**Comment by JustaFloatingEyeYT** [comment]
I think that latest.log file is the same as the last one, not sure what is happening.

**Comment by TelepathicGrunt** [comment]
Hmm. Using latest Bumblezone, Cardinal Components, Fabric API, and Cloth Config, I am not getting the same crash. It might be caused by another mod. Can you export your mod profile or mod folder so I can quickly test with that to see if it's another mod causing issues?
![image](https://user-images.githubusercontent.com/40846040/117866576-50161e80-b265-11eb-85e3-db4098e27b81.png)

**Comment by JustaFloatingEyeYT** [comment]
Also I added and removed some mods so the mod list will be different than the one I gave originally, sorry I have just been using the modpack without bumblezone (it is installed just disabled)

**Comment by TelepathicGrunt** [comment]
I disabled requiem and steel and the crash stopped. looking closer, it seems bumblezone's BeehiveBlockMixin is failing to be applied due to probably both of those mod's stuff. I'll look into them.

**Comment by JustaFloatingEyeYT** [comment]
Alright, also I got rid of steel because it was creating crashes with everything for me :/ also aether was missing the trinkets mod so I added that. (check the newer zip I sent to see those changes)

**Comment by TelepathicGrunt** [comment]
Oh it seems Requiem is using code directly from Bumblezone but as I updated, their code broke. I'll let them know to update

**Comment by JustaFloatingEyeYT** [comment]
Ok.

**Comment by JustaFloatingEyeYT** [comment]
Alright!

**Comment by JustaFloatingEyeYT** [comment]
Was fixed :D the new update on requiem worked, thanks.
