### ISSUE TITLE
Mod Compatibility Config is Wonky (Image)

### ISSUE THREAD

**Issue by queenielawrens** [TelepathicGrunt/Bumblezone-Fabric#30]
I have a feeling this isn't what it's supposed to say.
![image](https://user-images.githubusercontent.com/67487848/126701461-0d739910-cd1c-497f-97c5-b58725f2c681.png)

Version: 
BumbleZone: 3.0.6
Mod Menu: 2.0.3
Cardinal Components API: 3.1.0
Cloth Config: 5.0.34
Fabric API: 0.37.0
Minecraft: 1.17.1

**Comment by TelepathicGrunt** [comment]
yeah it just means the lang file is missing those two entries. that's all lol. It's suppose to say "Adds Bumblezone items to Charm's Beekeeper trades!"

I'll throw this in into next update

**Comment by TelepathicGrunt** [comment]
fixed in v3.0.7!
