### ISSUE TITLE
Bees eat everything?

### ISSUE THREAD

**Issue by kotx** [TelepathicGrunt/Bumblezone-Fabric#31]
Cobble, swords, enchanted items, air...

**Comment by TelepathicGrunt** [comment]
Can you explain what you mean by this? I do not modify bee behavior to eat items

**Comment by kotx** [comment]
> Can you explain what you mean by this? I do not modify bee behavior to eat items

In the README:
> - When feeding a Bee, you have a chance of getting Protection of the Hive effect where nearby Bees will attack anyone who attacked you!

This seems to make bees eat anything. However it could be a mod conflict.

**Comment by TelepathicGrunt** [comment]
The right click feeding is only suppose to work with honey bottle and other honey specific foods. I’ll double check the code but I thought you meant like bees burrowing through blocks or something lol. Always make your bug reports more specific as otherwise, I get confused lol.

**Comment by TelepathicGrunt** [comment]
![image](https://user-images.githubusercontent.com/40846040/127739121-0b194cd4-7411-40cc-9741-435dfdbdab01.png)
ah i had my code backwards lol. This should've been exiting the code early if the tag doesnt contain the item. Not when it contains the item.

v3.0.8 is now released and properly only allows what is in the_bumblezone:bee_feeding_items tag to be able to be fed to bees
