### ISSUE TITLE
Minecraft has crashed! I net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by TheButterbrotMan** [TelepathicGrunt/Bumblezone-Fabric#37]
Is crashing at starting

https://www.curseforge.com/minecraft/modpacks/deathdusk

https://pastebin.com/tvjmrND4

**Comment by TelepathicGrunt** [comment]
Does the crash go away if you remove direbats mod?

**Comment by TelepathicGrunt** [comment]
Direbats just updated to address this issue. Closing now
