### ISSUE TITLE
Underground beehives generate surface beehives when entering bumblezone

### ISSUE THREAD

**Issue by OdessaCubbage** [TelepathicGrunt/Bumblezone-Fabric#40]
I have a beehive at -51 Y deep underground. When I throw an enderpearl at it or use a piston to push myself into it instead puts me on the surface next to a newly generated beehive on the same X and Z coordinates as the first one, in this case on top of a mountain in the snow with no trees around. Entering this new beehive then works fine and takes me to the bumblezone. This happens at any negative Y coordinate.

**Comment by TelepathicGrunt** [comment]
Sounds like negative y is putting you in negative y Bumblezone which triggers code to exit Bumblezone. The y tries to be used to determine the y area you go to in Bumblezone but I guess I now have to make it a fixed y value now

**Comment by TelepathicGrunt** [comment]
fixed in v4.2.1

**Comment by OdessaCubbage** [comment]
Wow, thanks for the quick fix!
