### ISSUE TITLE
1.18.1 - FixedWaterlogging mod trying to make Honey Residue waterloggable

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone-Fabric#42]
It seems there's an unknown mod trying to make vines (i think?) waterloggable but that is killing my honey residue block badly.
https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric#c151

![image](https://user-images.githubusercontent.com/40846040/149626078-8d1c6fc9-a15c-40b0-b60e-0075f3e1158a.png)

Crashlog
https://paste.ee/p/nbwCl

This is the code that is crashing
https://imgur.com/k1bIeB0

**Comment by TelepathicGrunt** [comment]
New problematic mod:
https://github.com/KxmischesDomi/FixedWaterlogging/blob/1.18/src/main/java/de/kxmischesdomi/fixedwaterlogging/mixin/CreateBlockStateDefinitionMixin.java

**Comment by TheButterbrotMan** [comment]
https://pastebin.com/zRaxPpyh

**Comment by TelepathicGrunt** [comment]
@TheButterbrotMan yeah ik it crashes with FixedWaterlogging lol. You'll have to wait till they update to using Statement Library as when I tested with their dev jar using that library, it resolved the crash

**Comment by TelepathicGrunt** [comment]
Fixed now in latest Bumblezone update. My Sticky Honey Residue block no longer extends VineBlock and so, should not be getting that extra blockstate anymore from FixedWaterlogging. Hopefully
