### ISSUE TITLE
(Suggestion) Lighting sources for Bumblezone

### ISSUE THREAD

**Issue by StockiesLad** [TelepathicGrunt/Bumblezone-Fabric#46]
I really like the concept of this mod. It lacks light sources though.

[Glowing Honey Crystal]
This honey is spread out and dispersed everywhere and acts as a honey equivalent of glowstone. Simple and just adds a little more ambiance to the bumblezone.

**Comment by TelepathicGrunt** [comment]
I'll think about it but right now, candles is the current main light source at the moment. may change but next update is already finalized and coming out soon. Maybe a future update i'll think about if a new light source is really needed

**Comment by StockiesLad** [comment]
> I'll think about it but right now, candles is the current main light source at the moment. may change but next update is already finalized and coming out soon. Maybe a future update i'll think about if a new light source is really needed

Sounds great! Thank you for responding so quickly!
