### ISSUE TITLE
Fix requiem incompat

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone-Fabric#47]

**Comment by TelepathicGrunt** [comment]
v4.3.1 now has more compat hooks for requiem. Next requiem update should fix incompat

**Comment by Sunconure11** [comment]
Still running into this with the latest build of Bumblezone

**Comment by TelepathicGrunt** [comment]
@Sunconure11 Requiem hasn't updated yet to use the new bumblezone hooks and codebase. You have to wait a until their next update.

**Comment by TelepathicGrunt** [comment]
Requiem has updated to fix the crash now:
https://www.curseforge.com/minecraft/mc-mods/requiem/files/3852823
