### ISSUE TITLE
i dont go in with enderpearl

### ISSUE THREAD

**Issue by Worgrick** [TelepathicGrunt/Bumblezone-Fabric#5]

**Comment by TelepathicGrunt** [comment]
I’m gonna need more info as I was able to enter The Bumblezone when I was testing. Maybe I missed something. 

But let’s start with some troubleshooting first so I’ll know where to look and how to fix the issue. Did you throw the Enderpearl at a Beenest or Beehive? Did you have other mods on and if so, what mods were they? Was any configs changed? The Latest.log file will also greatly help too

**Comment by TelepathicGrunt** [comment]
I'm gonna close this issue has it has been over a week with no additional info. If you are still having issues, please re-open this issue with details such as which block are you throwing the pearl at and what mods you have on.
