### ISSUE TITLE
[Request] Please add a config

### ISSUE THREAD

**Issue by KMFrench1** [TelepathicGrunt/Bumblezone-Fabric#59]
Will you please add a config option to return to the same overworld coordinates that you entered the bumble dimension from. That way it feels like I am entering that specific hive and am leaving the same hive. Right now,  when leaving after exploring the bumblezone and appearing in a spot hundreds of blocks away does not feel like I was "in" the hive. 
I am not sure how hard that is to program, if it is an impossible task, thats ok just ignore me. :) Thanks for the great mod.

**Comment by KMFrench1** [comment]
Never mind, I found the config. It was already there. I am just blind. Sorry

**Comment by TelepathicGrunt** [comment]
No problem lol. Glad you found it!
