### ISSUE TITLE
Port to 1.18.2

### ISSUE THREAD

**Issue by kittech0** [TelepathicGrunt/Bumblezone-Fabric#61]
Port for fabric 1.18.2

**Comment by TelepathicGrunt** [comment]
@JustFoxx please stop. This and repurposed structures already are ported to 1.18.2. Check out my curseforge mod pages for the link. I'm going to block you from my github for about 10 minutes so you can see my message here instead of continuing on my other github pages.

**Comment by kittech0** [comment]
Sorry, but curseforge didnt showed for me that your mod has 1.18.2 update
