### ISSUE TITLE
[1.18.1] Adding bumblezone to an existing Terrablender world will not generate bumblezone dimension

### ISSUE THREAD

**Issue by TelepathicGrunt** [TelepathicGrunt/Bumblezone-Fabric#62]
https://github.com/Glitchfiend/TerraBlender/issues/38

Terrablender has to fix this on their end. That mod will prevent my mod's dimension from generating if my mod is added after the world is made. Meaning, You have to start the world in single player with the dimension and then move the world to the server. or maybe temporarily remove terrablender, start world, exit world, and then readd terrablender. Be sure to make a backup first

**Comment by CDAGaming** [comment]
This can probably be pinned/closed, considering this isnt going to be fixed in .1, but has been in 1.18.2

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/159187974-6573b8cd-4d31-4fd3-ad0a-03fdcb8c8070.png)

Specific instructions for those in need of a workaround
