### ISSUE TITLE
Friends and Foes Incompatibility 

### ISSUE THREAD

**Issue by SHXRKIEgg** [TelepathicGrunt/Bumblezone-Fabric#64]
Crash

[crash-2022-03-31_00.18.24-server.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/8388751/crash-2022-03-31_00.18.24-server.txt)

**Comment by TelepathicGrunt** [comment]
fixed now with https://github.com/TelepathicGrunt/Bumblezone-Fabric/commit/89b682b152b580db41b83ef16a5497549f0423d0
