### ISSUE TITLE
Crash when starting (1.18.2) | RuntimeException

### ISSUE THREAD

**Issue by Kroko1337** [TelepathicGrunt/Bumblezone-Fabric#65]
crash log: https://pastebin.com/ENZhrBZD

**Comment by TelepathicGrunt** [comment]
please remove optifine and optifabric and try again. If it is does not crash, then the issue is with optifine wrecking mc's source code in a way that I cannot be easily compatible with.

**Comment by TelepathicGrunt** [comment]
closing as no further info was provided. Gonna assume it was indeed optifine that was the issue
