### ISSUE TITLE
Crash upon rendering player with cosmetic armor mod

### ISSUE THREAD

**Issue by EmeraldRalts** [TelepathicGrunt/Bumblezone-Fabric#66]
[crash-2022-04-27_23.56.28-client.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/8579424/crash-2022-04-27_23.56.28-client.txt)

Upon rendering a player with HoneyBee equipment equipped, with cosmetic armor mod overriding the equipment, game crashes. Have tested other modded armors and none have resulted in a crash in the same manner.

How to recreate:
Equip Bumble Bee Chestplate in main armor slot
Equip any other armor in cosmetic armor slot 
Render player, either by opening inventory or pressing F5

**Comment by TelepathicGrunt** [comment]
Looking at their GitHub, they are crashing with other mod’s armor. I’m going to make a bug report on their GitHub instead as this seems more like an issue on cosmetic armor mod’s side I think. Or at the very least, they can explain what’s going on and what needs to be done on my end to not break how that mod works with their mixins that is showing up in your stacktrace. 

https://github.com/apace100/cosmetic-armor/issues

**Comment by TelepathicGrunt** [comment]
Cosmetic Armor just updated to fix the incompatibility they had with Geckolib. Now Bumblezone armor should no longer crash with those two mods on. Update Cosmetic Armor and give it a shot!
