### ISSUE TITLE
Server crash after updating to 5.1.1

### ISSUE THREAD

**Issue by SplendidAlakey** [TelepathicGrunt/Bumblezone-Fabric#69]
**MC** 1.18.2
**Fabric API** 0.53.4
**Bumblezone** 5.1.1

After updating from 5.0.14 the server no longer starts, shows the following error: https://gist.github.com/Footage2-Amply-Pounce/8316eb869eac3bf9e2ff513a185ee586

Version 5.1.0 is also affected. Last working version is 5.0.14.

Client is not affected.

**Comment by TelepathicGrunt** [comment]
fixed in v5.1.2 which is released now. I forgot to test server and ended up calling clientside code in a spot that the server was reading and crashing on. Thank you for reporting this!
