### ISSUE TITLE
Game crashes at the Bumblezone world border - Fabric 1.19/1.18.2

### ISSUE THREAD

**Issue by ImpSpy2** [TelepathicGrunt/Bumblezone-Fabric#71]
[crash-2022-07-19_05.54.48-server.txt](https://github.com/TelepathicGrunt/Bumblezone-Fabric/files/9137673/crash-2022-07-19_05.54.48-server.txt)

**Comment by TelepathicGrunt** [comment]
Bigger question is why the heck are you at world border lol

**Comment by ImpSpy2** [comment]
Just testing for a personal modpack, I guess you could say I like to be thorough 😄

**Comment by TelepathicGrunt** [comment]
fixed in v6.1.0
