### ISSUE TITLE
Crashing after world loads

### ISSUE THREAD

**Issue by tubesteakpiledriver** [TelepathicGrunt/Bumblezone-Fabric#78]
I don't know anything about java, I looked and can't find a solution, does anybody know if Bumblezone is the issue here? I could be an idiot for sure, but it looks like Bumblezone has something to do w it? I just don't want to start another world, especially if I cant figure out what happened. Sorry for my ignorance, any help is appreciated.

Time: 8/5/22, 5:05 PM
Description: Exception ticking world

java.lang.NullPointerException: Cannot read field "field_6002" because "player" is null
	at com.telepathicgrunt.the_bumblezone.entities.BeeAggression.preventAngerOnEssencedPlayers(BeeAggression.java:272)
	at net.minecraft.class_4482.handler$fpe000$thebumblezone_essenceBeehive1(class_4482.java:528)
	at net.minecraft.class_4482.method_21850(class_4482.java:111)
	at net.minecraft.class_4481.method_9559(class_4481.java:316)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:979)
	at net.minecraft.class_7165.method_42393(class_7165.java:35)
	at net.minecraft.class_7159$class_7272.method_41707(class_7159.java:143)
	at net.minecraft.class_7159.method_41702(class_7159.java:78)
	at net.minecraft.class_7159.method_41706(class_7159.java:65)
	at net.minecraft.class_7159.method_42392(class_7159.java:32)
	at net.minecraft.class_1937.method_42308(class_1937.java:343)
	at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:922)
	at net.minecraft.class_1937.method_30092(class_1937.java:255)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_2358.method_9588(class_2358.java:163)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:943)
	at net.minecraft.class_3218.method_14189(class_3218.java:700)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.telepathicgrunt.the_bumblezone.entities.BeeAggression.preventAngerOnEssencedPlayers(BeeAggression.java:272)
	at net.minecraft.class_4482.handler$fpe000$thebumblezone_essenceBeehive1(class_4482.java:528)
	at net.minecraft.class_4482.method_21850(class_4482.java:111)
	at net.minecraft.class_4481.method_9559(class_4481.java:316)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:979)
	at net.minecraft.class_7165.method_42393(class_7165.java:35)
	at net.minecraft.class_7159$class_7272.method_41707(class_7159.java:143)
	at net.minecraft.class_7159.method_41702(class_7159.java:78)
	at net.minecraft.class_7159.method_41706(class_7159.java:65)
	at net.minecraft.class_7159.method_42392(class_7159.java:32)
	at net.minecraft.class_1937.method_42308(class_1937.java:343)
	at net.minecraft.class_4970$class_4971.method_26183(class_4970.java:922)
	at net.minecraft.class_1937.method_30092(class_1937.java:255)
	at net.minecraft.class_1937.method_8652(class_1937.java:206)
	at net.minecraft.class_2358.method_9588(class_2358.java:163)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:943)
	at net.minecraft.class_3218.method_14189(class_3218.java:700)
	at net.minecraft.class_6757.method_39390(class_6757.java:215)
	at net.minecraft.class_6757.method_39377(class_6757.java:98)
	at net.minecraft.class_3218.method_18765(class_3218.java:308)

-- Affected level --
Details:
	All players: 1 total; [class_3222['My_S_Key_Broke'/143, l='ServerLevel[WHat]', x=-820.66, y=71.00, z=1716.43]]
	Chunk stats: 4754
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,75,0), Section: (at 0,11,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5139222 game time, 6175667 day time
	Level name: WHat
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 37079 (now: false), thunder time: 8674 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 956113336 bytes (911 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1179
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21931.02
	Virtual memory used (MB): 17755.59
	Swap memory total (MB): 5632.00
	Swap memory used (MB): 61.96
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
			libgui: LibGui 6.0.0-beta.5+1.19-pre1
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.6.1+1.19
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.14
		animatica: Animatica 0.5+1.19
		another_furniture: Another Furniture 2.0.1-1.19
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 5.10.33
		attributefix: AttributeFix 15.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.1.2
		bcc: BetterCompatibilityChecker fabric-2.0.1-build.15
		bclib: BCLib 2.0.16
		betteradvancements: Better Advancements 0.2.2.136
		betterend: Better End 2.0.9
		betterf3: BetterF3 1.3.2
		betternether: Better Nether 7.0.6
		betterthirdperson: Better Third Person 1.8.1
		bhmenu: BHMenu-Fabric 1.19-1.3
		biomemakeover: Biome Makeover 1.19-1.5.9
		blockus: Blockus 2.5.1+1.19
			terraform-wood-api-v1: Terraform Wood API (v1) 4.1.0
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 14.1.7
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.1-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		byg: Oh The Biomes You'll Go 2.0.0.7
		capybara: Capybara 1.0.5
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0-beta.2+1.19
		charmonium: Charmonium 4.1.0
		cherishedworlds: Cherished Worlds 6.0.0-beta.2+1.19
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cleancut: CleanCut 1.19-5.0-fabric
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v6 7.0.73
		clumps: Clumps 9.0.0+6
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		colormatic: Colormatic 3.1.2+mc.1.19
		comforts: Comforts 6.0.0-beta.4+1.19
			spectrelib: SpectreLib 0.8.1+1.19
		continuity: Continuity 2.0.0+1.19
		controlling: Controlling For Fabric 10.0+3
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		cull-less-leaves: Cull Less Leaves 1.0.4
			com_github_llamalad7_mixinextras: mixinextras 0.0.11
			conditional-mixin: conditional mixin 0.3.0
		darkpaintings: DarkPaintings 11.0.2
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.3.2
		deepslatecutting: Deepslate Cutting 1.4.0
		dragonloot: DragonLoot 1.1.1
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		duckling: Duckling 2.0.3
		dungeons_arise: When Dungeons Arise 2.1.51
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.2.0
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		earthtojavamobs: Earth2Java 1.9.2
		easymagic: Easy Magic 4.0.0
		ecologics: Ecologics 2.1.4
		edenring: EdenRing 0.6.3
		effective: Effective 1.2.2
		enchdesc: EnchantmentDescriptions 11.0.4
		enhancedcelestials: Enhanced Celestials 2.1.0.0
		entity_texture_features: Entity Texture Features 4.0
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		expandeddelight: Expanded Delight 0.2.1
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric: Fabric API 0.58.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.28+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.1+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.2+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.26+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.5+35a03c43a9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.26+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.1+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.4+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.11+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.1.0+442de8b8a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.15+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.8+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.18+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.10+5187d39fa9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.6+5f1a85e0a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.7+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fallingleaves: Falling Leaves 1.12.1+1.19
		fallingtree: FallingTree 3.7.4
		fancymenu: FancyMenu 2.11.1
		farmersdelight: Farmer's Delight 1.19-0.3.0
		farmersknives: Farmer's Knives 2.0
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.0.0
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.24.0+1.19
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.5.5
		ftbchunks: FTB Chunks 1900.3.8-build.157
		ftblibrary: FTB Library 1900.3.8-build.135
		ftbteams: FTB Teams 1900.2.8-build.59
		fwaystones: Fabric Waystones 3.0.2+mc1.19
		galosphere: Galosphere 1.19-1.1.0-fabric
		geckolib3: Geckolib 3.1.6
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.4
		goblintraders: Goblin Traders 1.5.2
		graveyard: The Graveyard 1.10
		guardvillagers: Guard Villagers Fabric 1.19-1.0.16
		highlighter: Highlighter 1.1.2
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.8
		immersive_weathering: Immersive Weathering 1.0.1-1.19_SNAPSHOT
		impactfulweather: Biome Particle Weather 4.0.1
		imst: Immersive structures 2.0.2
		indium: Indium 1.0.6+mc1.19
		infusion_table: Infusion Table 1.1.0
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.3.2
		java: OpenJDK 64-Bit Server VM 17
		just_end_anchor: Just An End Anchor 1.0.2
		konkrete: Konkrete 1.4.0
		krypton: Krypton 0.2.0
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.1
		magnumtorch: Magnum Torch 4.0.1
		mavm: More Axolotl Variants Mod 1.1.0
		memoryleakfix: memory Leak Fix 1.19-0.5.4
		merchantmarkers: Merchant Markers 1.2.2
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19
		modid: Creatures Of The Snow 2.2.0+1.19
		modmenu: Mod Menu 4.0.4
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 0.5.3
		moremcmeta: MoreMcmeta 1.19-3.0.5
		moretotems: More Totems 2.11.0
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		naturalist: Naturalist 2.0.1
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		nears: Nears 1.2.2
		nochatreports: No Chat Reports 1.19-v1.2.3
		notenoughanimations: NotEnoughAnimations 1.6.0
		onsoulfire: On Soul Fire 1.19-2
		openloader: OpenLoader 13.0.1
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		oxidized: Oxidized 1.7.1
		paintings: Paintings++ 10.0.0.0
		patchouli: Patchouli 1.19-74-FABRIC
		pickupnotifier: Pick Up Notifier 4.0.0
		plushies: Plushie Mod 1.2
		puzzle: Puzzle 1.3.4-1.19
			puzzle-base: Puzzle Base 1.3.4-1.19
			puzzle-gui: Puzzle GUI 1.3.4-1.19
			puzzle-models: Puzzle Models 1.3.4-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.3.4-1.19
		puzzleslib: Puzzles Lib 4.0.17
		quartzelv: Quartz Elevator 2.1.3+1.19
		reeses-sodium-options: Reese's Sodium Options 1.4.4+mc1.19-build.47
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 2.2.1
		rocks: This Rocks! 1.6.1
		roughlyenoughitems: Roughly Enough Items 9.1.517
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		sdrp: Simple Discord Rich Presence 2.0.0-build.13+mc1.19
		seasons: Fabric Seasons 1.4-BETA+1.19
		simple_shelves: Simple Shelves 1.1.0
		skinlayers: 3d Skin Layers 1.4.7-mc1.19
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spark: spark 1.9.26
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		spirit: Spirit 2.1.2
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.3
		steves_vanilla: Steves Vanilla 1.0.0+1.19
		stoneholm: Stoneholm 1.4.4
		structory: Structory 1.0.1
		t_and_t: Towns and Towers - Structure Add-on 1.8
		terrablender: TerraBlender 2.0.0.120
		the_bumblezone: The Bumblezone - Fabric 6.1.1+1.19
			fake-player-api: Fake Player API 0.3.0
		thonkutil: ThonkUtil 2.15.3+1.19
			thonkutil-base: ThonkUtil Base 1.13.1+575521ba57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.1+7ce8ef6257
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.1+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.1+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.1+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.1+8ff533c957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.1+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.1+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.1+8ff533c957
		tipsmod: Tips 6.0.1
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 10.0.1
		tooltipfix: ToolTip Fix 1.0.5-1.19
		tradingpost: Trading Post 4.0.0
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		universal_ores: Universal Ores 1.4.1
		villagernames: Villager Names 4.0.5
		visuality: Visuality 0.5.0
		visualworkbench: Visual Workbench 4.0.0
		voidtotem: Void Totem 2.0.0
		voidz: VoidZ 1.0.8
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			coat: Coat 1.0.0-beta.18+mc22w17a
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data: tweed4_data 1.2.1+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc22w17a
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc22w17a
		wardentools: Warden Tools 1.0
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 5.7.0
		xaerominimap: Xaero's Minimap 22.12.0
		xaeroworldmap: Xaero's World Map 1.26.1
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
		zoomify: Zoomify 1.7.1
			dev_isxander_settxi_settxi-core: settxi-core 2.4.0
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.4.0
			settxi-gui-cloth-config: Settxi Gui (Cloth Config) 2.4.0
	Loaded Shaderpack: BSL_v8.1.02.3.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['My_S_Key_Broke'/143, l='ServerLevel[WHat]', x=-820.66, y=71.00, z=1716.43]]
	Data Packs: vanilla, Fabric Mods, data/Repurposed_Structures-Friends_And_Foes-v2.zip, data/Repurposed_Structures-More_Villagers_v7.zip, data/dungeons-arise-1-19-v1-1.zip, data/ichphilipp-s-endcity-better-end-1-18-1.zip (incompatible)
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.14.8-1.19

**Comment by TelepathicGrunt** [comment]
Please update fabric Bumblezone to v6.1.4 as I already fixed this issue in that version. Here’s part of the changelog:

Mod Compat:
Fixed crash if a mod passes null into beehivetileentity.emptyAllLivingFromHive. I added a null check to my code to prevent a crash.

that should resolve your crash for good. Hope this helps!
