### ISSUE TITLE
I can't see in the Bee Dim.

### ISSUE THREAD

**Issue by Devilchill** [TelepathicGrunt/Bumblezone-Fabric#83]
Im currently in a modded minecraft server with some friends, everyone one else that entered the Bee Dimension has no problems, but when i enter i cannot see anything but the ceiling, i have no clue what to do, and i havent seen anyone one else with this issue, Help :C
![image](https://user-images.githubusercontent.com/123039802/213335449-24ca9db7-e9fa-4b8c-8b2f-7693ad58cef1.png)

**Comment by TelepathicGrunt** [comment]
Just fyi, this is my dead repo. Please use the current Bumblezone repo here which has an issue report already detailing your problem: https://github.com/TelepathicGrunt/Bumblezone/issues/193

The short workaround is to lower the fogReducer config in Bumblezone’s config to 3.25 or so and it should render properly. Or reduce the render distance to below 30. Next Bumblezone update 1.19.2+ will redo that config and implementation to handle fog better for all render distance
